import type { TurkishCulturalColor } from './types';

export const TURKISH_CULTURE_COLORS: TurkishCulturalColor[] = [
  {
    id: 'kirmizi',
    nameTr: 'Kırmızı',
    nameEn: 'Red',
    historicalName: 'Al / Kızıl',
    hex: '#E30A17',
    cosmologicalDirection: 'south',
    meanings: ['güç', 'cesaret', 'bağımsızlık', 'devlet', 'yaşam'],
    description:
      "Türk bayrağının rengi; cesaret, güç ve yaşamı simgeler. Eski Türkçede 'Kızıl' olarak geçer, kozmolojik yön sisteminde güneyi temsil eder.",
    origin: 'Türk bayrağı, eski Türk yön-renk kozmolojisi',
    usages: ['Türk bayrağı', 'geleneksel kıyafetler', 'halı ve kilim'],
    promptKeyword: 'vivid crimson red, Turkish flag red, bold fiery tone',
    category: 'colors',
  },
  {
    id: 'beyaz',
    nameTr: 'Beyaz',
    nameEn: 'White',
    historicalName: 'Ak / Beyaz',
    hex: '#FFFFFF',
    cosmologicalDirection: 'west',
    meanings: ['saflık', 'barış', 'iyilik', 'aydınlık', 'arınma'],
    description:
      "Saflık, barış ve arınmayı simgeler; bayraktaki ay-yıldızın rengi. Eski Türkçede 'Ak' olarak geçer, yön sisteminde batıyı temsil eder.",
    origin: 'Türk bayrağı, eski Türk yön-renk kozmolojisi',
    usages: ['geleneksel sembolizm', 'kıyafet', 'dokuma'],
    promptKeyword: 'pure white, crescent moon white, clean luminous tone',
    category: 'colors',
  },
  {
    id: 'turkuaz',
    nameTr: 'Turkuaz',
    nameEn: 'Turquoise',
    historicalName: 'Firuze / Türkuaz',
    hex: '#17A398',
    meanings: ['Türklük', 'gökyüzü', 'özgürlük', 'koruyuculuk', 'şifa'],
    description:
      'İznik çinilerinin ve nazar boncuğunun ana rengi; kötülüğe karşı koruma ve şifa taşıdığına inanılır. Batı dillerine Türk taşı anlamında girmiştir.',
    origin: 'İznik çiniciliği, nazar boncuğu geleneği, Osmanlı dönemi',
    usages: ['çini', 'mimari', 'takı', 'dekoratif sanatlar'],
    promptKeyword:
      'turquoise glaze, protective evil-eye blue-green, Iznik ceramic tone',
    category: 'colors',
  },
  {
    id: 'cini-mavisi',
    nameTr: 'Çini Mavisi',
    nameEn: 'Tile Blue (Cobalt)',
    historicalName: 'Kobalt Mavi',
    hex: '#1B4F91',
    meanings: ['huzur', 'maneviyat', 'derinlik', 'sonsuzluk'],
    description:
      'Cami kubbelerini ve İznik çinilerini süsleyen koyu kobalt mavi; huzur ve maneviyatı çağrıştırır.',
    origin: 'İznik çiniciliği, Osmanlı cami mimarisi (örn. Sultanahmet Camii)',
    usages: ['çini', 'seramik', 'kubbe süslemeleri', 'hat sanatı'],
    promptKeyword: 'deep cobalt blue, Ottoman tile blue, mosque dome hue',
    category: 'colors',
  },
  {
    id: 'gok-mavisi',
    nameTr: 'Gök Mavisi',
    nameEn: 'Sky Blue',
    historicalName: 'Gök Mavisi',
    hex: '#4A90D9',
    cosmologicalDirection: 'east',
    meanings: ['gök', 'sonsuzluk', 'özgürlük', 'Gök Tanrı inancı'],
    description:
      "Eski Türk inancındaki 'Gök Tengri' kültüyle bağlantılı gökyüzü mavisi; sonsuzluk ve kutsallığı simgeler, yön sisteminde doğuyu temsil eder.",
    origin: 'Göktürk dönemi, Gök Tengri inancı, Orta Asya Türk kültürü',
    usages: ['bayrak ve süslemeler', 'geleneksel motifler', 'freskler'],
    promptKeyword:
      'open sky blue, celestial Tengri blue, boundless heaven tone',
    category: 'colors',
  },
  {
    id: 'lacivert',
    nameTr: 'Lacivert',
    nameEn: 'Navy Blue',
    historicalName: 'Gece Mavisi',
    hex: '#14213D',
    meanings: ['otorite', 'derinlik', 'asalet', 'gece göğü'],
    description:
      'Asalet ve derinliği simgeler; Osmanlı kaftan ve kumaşlarında, seramik ve çinilerinde sıkça kullanılan koyu gece mavisi.',
    origin: 'Osmanlı saray tekstili ve çiniciliği',
    usages: ['Osmanlı çinileri', 'kumaş', 'seramik', 'saray kaftanları'],
    promptKeyword: 'deep navy, royal midnight blue, rich Ottoman fabric tone',
    category: 'colors',
  },
  {
    id: 'nar-kirmizisi',
    nameTr: 'Nar Kırmızısı',
    nameEn: 'Pomegranate Red',
    historicalName: 'Nar Çiçeği',
    hex: '#C41E3A',
    meanings: ['bereket', 'bolluk', 'canlılık', 'doğurganlık'],
    description:
      'Bereket ve bolluğun simgesi; kilim, çini ve halı motiflerinde sıkça görülen zengin ve sıcak kırmızı ton.',
    origin: 'Anadolu halk sanatı, antik Anadolu bereket sembolizmi',
    usages: ['dokuma', 'kilim', 'çini', 'geleneksel el sanatları'],
    promptKeyword:
      'pomegranate red, fertility crimson, rich fruit-inspired tone',
    category: 'colors',
  },
  {
    id: 'kina-rengi',
    nameTr: 'Kına Rengi',
    nameEn: 'Henna',
    historicalName: 'Kına Kızılı',
    hex: '#A0522D',
    meanings: ['bereket', 'kutlama', 'bağlılık', 'geçiş ritüelleri'],
    description:
      'Kına gecesi geleneğiyle özdeşleşmiş kızıl-kahve ton; bereket, kutlama ve aile bağlarını temsil eder.',
    origin: 'Anadolu düğün ve kına gelenekleri',
    usages: ['kına ritüelleri', 'geleneksel dokuma', 'deri işlemeciliği'],
    promptKeyword: 'henna red-brown, wedding night warmth, earthy reddish tone',
    category: 'colors',
  },
  {
    id: 'toprak-rengi',
    nameTr: 'Toprak Rengi',
    nameEn: 'Terracotta',
    historicalName: 'Toprak Kahvesi',
    hex: '#B5651D',
    meanings: ['toprak', 'Anadolu', 'doğallık', 'kökler', 'bağlılık'],
    description:
      'Anadolu toprağını ve geleneksel çömlekçiliği çağrıştıran sıcak kahverengi-turuncu ton.',
    origin: 'Anadolu çömlekçilik ve seramik geleneği',
    usages: ['seramik', 'çömlekçilik', 'kilim', 'Anadolu motifleri'],
    promptKeyword:
      'terracotta clay, warm Anatolian earth tone, sun-baked orange-brown',
    category: 'colors',
  },
  {
    id: 'zeytin-yesili',
    nameTr: 'Zeytin Yeşili',
    nameEn: 'Olive Green',
    historicalName: 'Zeytuni',
    hex: '#6B8E23',
    meanings: ['barış', 'bereket', 'sağlık', 'doğa', 'uzun ömür'],
    description:
      'Ege ve Akdeniz kültürünün simgesi; barış, bereket ve sağlığı temsil eden zeytin ağacından gelir.',
    origin: 'Ege bölgesi zeytincilik ve doğa kültürü',
    usages: ['tekstil', 'çini desenleri', 'peyzaj ve mimari süsleme'],
    promptKeyword: 'muted olive green, Aegean grove tone, natural calm hue',
    category: 'colors',
  },
  {
    id: 'bakir',
    nameTr: 'Bakır',
    nameEn: 'Copper',
    historicalName: 'Bakır Rengi',
    hex: '#B87333',
    meanings: ['sıcaklık', 'el emeği', 'zanaat', 'çarşı kültürü'],
    description:
      'Geleneksel bakırcılık zanaatının rengi; sıcaklık, el emeği ve Anadolu çarşı kültürünü simgeler.',
    origin: 'Anadolu bakırcılık zanaatı (Gaziantep, Diyarbakır, Tokat)',
    usages: ['bakır işleme', 'mutfak eşyaları', 'dekoratif sanatlar'],
    promptKeyword: 'polished copper, warm metallic bazaar tone, artisanal glow',
    category: 'colors',
  },
  {
    id: 'altin-sarisi',
    nameTr: 'Altın Sarısı',
    nameEn: 'Gold',
    historicalName: 'Altın Sarısı',
    hex: '#D4AF37',
    cosmologicalDirection: 'center',
    meanings: ['zenginlik', 'güneş', 'hükümdarlık', 'ihtişam', 'merkez'],
    description:
      'Osmanlı sarayının ihtişamını, güneşi ve zenginliği simgeler; eski Türk yön sisteminde merkezi temsil eden sarı rengin en parlak hali.',
    origin: 'Osmanlı saray sanatı, tezhip, minyatür ve mücevher geleneği',
    usages: ['tezhip', 'saray dekorasyonu', 'işlemeler', 'hat tezhibi'],
    promptKeyword: 'royal gold, sun-gilded ornament, opulent Ottoman shine',
    category: 'colors',
  },
  {
    id: 'erguvan',
    nameTr: 'Erguvan',
    nameEn: 'Judas-tree Purple',
    historicalName: 'Erguvani',
    hex: '#9C4F96',
    meanings: ['bahar', 'zarafet', 'Boğaziçi', 'şiirsel asalet'],
    description:
      "İstanbul'un baharını müjdeleyen erguvan çiçeğinin rengi; Divan şiirinde ve Boğaziçi manzaralarında sıkça anılır.",
    origin: 'İstanbul/Boğaziçi doğası, Divan şiiri ve Osmanlı bahar şenlikleri',
    usages: ['edebiyat', 'kumaş boyacılığı', 'peyzaj sanatı'],
    promptKeyword:
      'Judas-tree magenta-purple, Bosphorus spring bloom, soft poetic violet',
    category: 'colors',
  },
  {
    id: 'safran-sarisi',
    nameTr: 'Safran Sarısı',
    nameEn: 'Saffron Yellow',
    historicalName: 'Safran',
    hex: '#F4C430',
    meanings: ['güneş', 'canlılık', 'ticaret', 'şifa', 'enerji'],
    description:
      'Baharat ticareti ve doğal boyacılıkta kullanılan parlak sarı; zenginlik, şifa ve canlılığı simgeler.',
    origin: 'Safranbolu safran kültürü, Anadolu baharat ve boyacılık geleneği',
    usages: ['doğal boyacılık', 'hat sanatı mürekkepleri', 'gastronomi'],
    promptKeyword: 'saffron yellow, spice-market gold, vivid warm hue',
    category: 'colors',
  },
  {
    id: 'kara',
    nameTr: 'Kara / Siyah',
    nameEn: 'Black',
    historicalName: 'Kara',
    hex: '#1A1A1A',
    cosmologicalDirection: 'north',
    meanings: ['güç', 'derinlik', 'kuzey', 'ciddiyet', 'toprak'],
    description:
      "Eski Türk yön sisteminde kuzeyi temsil eder (örn. 'Karadeniz' adlandırması); güç, otorite ve derinliği simgeler.",
    origin: 'Eski Türk yön-renk kozmolojisi, Orta Asya dokuma geleneği',
    usages: ['dokuma', 'hat sanatı is mürekkebi', 'geleneksel motifler'],
    promptKeyword: 'deep black, northern steppe shadow, grounded powerful tone',
    category: 'colors',
  },
  {
    id: 'yesil',
    nameTr: 'Yeşil',
    nameEn: 'Green',
    historicalName: 'Yeşil / Çimen',
    hex: '#2E7D32',
    meanings: ['doğa', 'yaşam', 'bereket', 'yenilenme', 'huzur'],
    description:
      'Tabiatın uyanışını, bereketi ve manevi huzuru simgeler; Selçuklu ve Osmanlı mimarisinde sıklıkla tercih edilmiştir.',
    origin: 'Anadolu doğa kültürü, Selçuklu çini sanatı',
    usages: ['çini', 'mimari', 'kilim', 'geleneksel sanat'],
    promptKeyword:
      'lush emerald green, Anatolian spring flora, peaceful natural green',
    category: 'colors',
  },
];
